<a href="https://www.kaggle.com/code/tanjimulislam2209/assignment-3-2-tanjimul-islam?scriptVersionId=348252106" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv
/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/binib1997/superstore/Superstore.csv
/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTest.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import datasets on a dataframe

In [3]:
store = pd.read_csv('/kaggle/input/datasets/binib1997/superstore/Superstore.csv', encoding='latin-1')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
iris = pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
climate = pd.read_csv('/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv')

# Series

# 1. Create a series from a list

In [4]:
age= [18,20,19,21,22]
age= pd.Series(age)
age

0    18
1    20
2    19
3    21
4    22
dtype: int64

# 2. Create series from a dictionary

In [5]:
marks={
    'Rahim':85,
    'Karim':72,
    'Hasan':91,
    'Sakib':78
}
marks=pd.Series(marks)
marks

Rahim    85
Karim    72
Hasan    91
Sakib    78
dtype: int64

# 3. Create a series from dataframe

In [6]:
data = pd.DataFrame({
    'name': ['Rahim','Karim','Hasan','Sakib'],
    'age': [18,20,19,21],
    'marks': [85,72,91,78]
})
series = pd.Series(data['age'])
series

0    18
1    20
2    19
3    21
Name: age, dtype: int64

# 4. Apply below operations on a series to understand about a series

In [7]:
series.head()

0    18
1    20
2    19
3    21
Name: age, dtype: int64

In [8]:
series.tail()

0    18
1    20
2    19
3    21
Name: age, dtype: int64

In [9]:
series.sample(2)

3    21
0    18
Name: age, dtype: int64

In [10]:
series.size

4

In [11]:
series.dtype

dtype('int64')

In [12]:
series.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
series.values

array([18, 20, 19, 21])

# 5. Change data-type of a series

In [14]:
series.astype(float)

0    18.0
1    20.0
2    19.0
3    21.0
Name: age, dtype: float64

# 6. Apply below mathematical operations on a series

In [15]:
series.count()

np.int64(4)

In [16]:
series.sum()

np.int64(78)

In [17]:
series.product()

np.int64(143640)

In [18]:
series[-2:]

2    19
3    21
Name: age, dtype: int64

# 7. Do 3 slicing operations on a series

In [19]:
series[:3]

0    18
1    20
2    19
Name: age, dtype: int64

In [20]:
series[1:4]

1    20
2    19
3    21
Name: age, dtype: int64

# Dataframe

# 1. Create a dataframe from a list

In [21]:
students= [['Rahim', 'CSE', 85],['Karim', 'EEE', 72],['Hasan', 'BBA', 91],['Sakib', 'CSE', 78]]
df = pd.DataFrame(students, columns=['name', 'department', 'marks'])
df

    name department  marks
0  Rahim        CSE     85
1  Karim        EEE     72
2  Hasan        BBA     91
3  Sakib        CSE     78

# 2. Apply below dataframe understanding operations

In [22]:
df.head()

    name department  marks
0  Rahim        CSE     85
1  Karim        EEE     72
2  Hasan        BBA     91
3  Sakib        CSE     78

In [23]:
df.tail()

    name department  marks
0  Rahim        CSE     85
1  Karim        EEE     72
2  Hasan        BBA     91
3  Sakib        CSE     78

In [24]:
df.sample(3)

    name department  marks
2  Hasan        BBA     91
0  Rahim        CSE     85
3  Sakib        CSE     78

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   department  4 non-null      object
 2   marks       4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

# 2. Apply below dataframe attribute operations

In [26]:
df.shape

(4, 3)

In [27]:
df.shape

(4, 3)

# 3. Apply below mathematical operations on a feature taken from dataframe

In [28]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [29]:
df['marks'].count()

np.int64(4)

In [30]:
df['marks'].sum()

np.int64(326)

In [31]:
df['marks'].product()

np.int64(43439760)

In [32]:
df['marks'].min()

72

In [33]:
df['marks'].max()

91

In [34]:
df['marks'].mean()

np.float64(81.5)

In [35]:
df['marks'].median()

81.5

In [36]:
df['marks'].mode()

0    72
1    78
2    85
3    91
Name: marks, dtype: int64

In [37]:
df['marks'].describe()

count     4.000000
mean     81.500000
std       8.266398
min      72.000000
25%      76.500000
50%      81.500000
75%      86.500000
max      91.000000
Name: marks, dtype: float64

In [38]:
df['marks'].std()

8.266397845091497

In [39]:
df['marks'].var()

68.33333333333333

# Selection and filtering

In [40]:
# loc
# iloc
# isin()
# logical operation (&, |, ~)

# 1. Select 11-20th rows and total_bill and tip columns from tips dataframe

In [41]:
tips.loc[10:20, ['sex', 'day']]

       sex  day
10    Male  Sun
11  Female  Sun
12    Male  Sun
13    Male  Sun
14  Female  Sun
15    Male  Sun
16  Female  Sun
17    Male  Sun
18  Female  Sun
19    Male  Sat
20    Male  Sat

# 2. Select 0-20th rows and total_bill, tip and day columns from tips dataframe

In [42]:
tips.loc[0:19, ['total_bill', 'tip', 'day']]

    total_bill   tip  day
0        16.99  1.01  Sun
1        10.34  1.66  Sun
2        21.01  3.50  Sun
3        23.68  3.31  Sun
4        24.59  3.61  Sun
5        25.29  4.71  Sun
6         8.77  2.00  Sun
7        26.88  3.12  Sun
8        15.04  1.96  Sun
9        14.78  3.23  Sun
10       10.27  1.71  Sun
11       35.26  5.00  Sun
12       15.42  1.57  Sun
13       18.43  3.00  Sun
14       14.83  3.02  Sun
15       21.58  3.92  Sun
16       10.33  1.67  Sun
17       16.29  3.71  Sun
18       16.97  3.50  Sun
19       20.65  3.35  Sat

# 3. Select customers who comes in sunday and total_bill is greater than 20 dollars

In [43]:
tips[(tips['day'] == 'Sun') & (tips['total_bill'] > 20)]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
11        35.26  5.00  Female     No  Sun  Dinner     4
15        21.58  3.92    Male     No  Sun  Dinner     2
44        30.40  5.60    Male     No  Sun  Dinner     4
46        22.23  5.00    Male     No  Sun  Dinner     2
47        32.40  6.00    Male     No  Sun  Dinner     4
48        28.55  2.05    Male     No  Sun  Dinner     3
52        34.81  5.20  Female     No  Sun  Dinner     4
54        25.56  4.34    Male     No  Sun  Dinner     4
112       38.07  4.00    Male     No  Sun  Dinner     3
113       23.95  2.55    Male     No  Sun  Dinner     2
114       25.71  4.00  Female     No  Sun  Dinner     3
116       29.93  5.07    Male     No  Sun  Dinner     4
153       24.55  2.00    Male     No  Sun  Dinner     4
155       29.85  5.14  Female     No  Sun  Dinner     5
156       48.17  5.00    Male     No  Sun  Dinner     6
157       25.00  3.75  Female     No  Sun  Dinner     4
160       21.50  3.50    Male     No  Sun  Dinner     4
165       24.52  3.48    Male     No  Sun  Dinner     3
166       20.76  2.24    Male     No  Sun  Dinner     2
167       31.71  4.50    Male     No  Sun  Dinner     4
173       31.85  3.18    Male    Yes  Sun  Dinner     2
175       32.90  3.11    Male    Yes  Sun  Dinner     2
179       34.63  3.55    Male    Yes  Sun  Dinner     2
180       34.65  3.68    Male    Yes  Sun  Dinner     4
181       23.33  5.65    Male    Yes  Sun  Dinner     2
182       45.35  3.50    Male    Yes  Sun  Dinner     3
183       23.17  6.50    Male    Yes  Sun  Dinner     4
184       40.55  3.00    Male    Yes  Sun  Dinner     2
185       20.69  5.00    Male     No  Sun  Dinner     5
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
189       23.10  4.00    Male    Yes  Sun  Dinner     3

# 4. Select passengers who are male and age greater than 50 from titanic

In [44]:
titanic[(titanic['Sex'] == 'male') & (titanic['Age'] > 50)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,NaN,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
262,263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.6500,E67,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
317,318,0,2,"Moraweck, Dr. Ernest",male,54.0,0,0,29011,14.0000,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
406,407,0,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C
492,493,0,1,"Molson, Mr. Harry Markland",male,55.0,0,0,113787,30.5000,C30,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
582,583,0,2,"Downton, Mr. William James",male,54.0,0,0,28403,26.0000,NaN,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
631,632,0,3,"Lundahl, Mr. Johan Svensson",male,51.0,0,0,347743,7.0542,NaN,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
714,715,0,2,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S

# 5. Select customers who are female and tip greater than 5 dollars from tips dataframe - write query operation

In [45]:
tips.query("sex == 'Female' and tip > 5")

     total_bill   tip     sex smoker   day    time  size
52        34.81  5.20  Female     No   Sun  Dinner     4
85        34.83  5.17  Female     No  Thur   Lunch     4
155       29.85  5.14  Female     No   Sun  Dinner     5
214       28.17  6.50  Female    Yes   Sat  Dinner     3

# groupby

# 1. group on region based in store dataframe

In [46]:
store.groupby('Region')['Customer Name'].count()

Region
Central    2323
East       2848
South      1620
West       3203
Name: Customer Name, dtype: int64

# 2. Find region-wise average sales

In [47]:
store.groupby('Region')['Sales'].mean()

Region
Central    215.772661
East       238.336110
South      241.803645
West       226.493233
Name: Sales, dtype: float64

# 3. Find region-wise average profit

In [48]:
store.groupby('Region')['Profit'].mean()

Region
Central    17.092709
East       32.135808
South      28.857673
West       33.849032
Name: Profit, dtype: float64

# 4. Find region-wise maximum profit

In [49]:
store.groupby('Region')['Profit'].max()

Region
Central    8399.9760
East       5039.9856
South      3177.4750
West       6719.9808
Name: Profit, dtype: float64

# 5. Apply multiple aggregate functions on region-wise sales

In [50]:
store.groupby('Region')['Sales'].agg(['sum', 'mean', 'min', 'max'])

                 sum        mean    min        max
Region
Central  501239.8908  215.772661  0.444  17499.950
East     678781.2400  238.336110  0.852  11199.968
South    391721.9050  241.803645  1.167  22638.480
West     725457.8245  226.493233  0.990  13999.960

# 6. group on region and category wise

In [51]:
store.groupby(['Region', 'Category'])['Order ID'].count()

Region   Category
Central  Furniture           481
         Office Supplies    1422
         Technology          420
East     Furniture           601
         Office Supplies    1712
         Technology          535
South    Furniture           332
         Office Supplies     995
         Technology          293
West     Furniture           707
         Office Supplies    1897
         Technology          599
Name: Order ID, dtype: int64

# 7. Find region and category wise average sales

In [52]:
store.groupby(['Region', 'Category'])['Sales'].mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

# 8. Find region and category wise average, minimumm, maximum and sum sales

In [53]:
store.groupby(['Region', 'Category'])['Sales'].agg(['mean', 'min', 'max', 'sum'])

                               mean    min        max          sum
Region  Category
Central Furniture        340.534644  1.892   3504.900  163797.1638
        Office Supplies  117.458801  0.444   9892.740  167026.4150
        Technology       405.753124  1.980  17499.950  170416.3120
East    Furniture        346.574383  2.960   4416.174  208291.2040
        Office Supplies  120.044425  0.852   4663.736  205516.0550
        Technology       495.278469  2.970  11199.968  264973.9810
South   Furniture        353.309289  2.784   4297.644  117298.6840
        Office Supplies  126.282727  1.167   6354.950  125651.3130
        Technology       507.753952  1.584  22638.480  148771.9080
West    Furniture        357.302325  3.480   3610.848  252612.7435
        Office Supplies  116.422377  1.080   8187.650  220853.2490
        Technology       420.687533  0.990  13999.960  251991.8320

# Merging and joining

In [54]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    "name": ["Rahim", "Karim", "Hasan", "Sakib", "Nabil",
             "Tanvir", "Fahim", "Rafi", "Imran", "Shakil",
             "Arif", "Jahid", "Mehedi", "Siam", "Tareq",
             "Rakib", "Adnan", "Nayeem", "Foysal", "Rony"],
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE",
                   "EEE", "CSE", "BBA", "CSE", "EEE",
                   "CSE", "BBA", "EEE", "CSE", "BBA",
                   "CSE", "EEE", "CSE", "BBA", "EEE"]
})

students

    student_id    name department
0          101   Rahim        CSE
1          102   Karim        EEE
2          103   Hasan        CSE
3          104   Sakib        BBA
4          105   Nabil        CSE
5          106  Tanvir        EEE
6          107   Fahim        CSE
7          108    Rafi        BBA
8          109   Imran        CSE
9          110  Shakil        EEE
10         111    Arif        CSE
11         112   Jahid        BBA
12         113  Mehedi        EEE
13         114    Siam        CSE
14         115   Tareq        BBA
15         116   Rakib        CSE
16         117   Adnan        EEE
17         118  Nayeem        CSE
18         119  Foysal        BBA
19         120    Rony        EEE

In [55]:
results = pd.DataFrame({
    "student_id": [101, 102, 103, 105, 106, 108, 109, 111, 112, 114,
                   121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
    "math": [85, 72, 91, 68, 77, 88, 74, 95, 81, 69,
             78, 84, 92, 73, 89, 67, 80, 94, 76, 83],
    "python": [90, 75, 88, 72, 80, 92, 79, 96, 85, 71,
               82, 87, 95, 76, 91, 70, 84, 93, 78, 86]
})

results

    student_id  math  python
0          101    85      90
1          102    72      75
2          103    91      88
3          105    68      72
4          106    77      80
5          108    88      92
6          109    74      79
7          111    95      96
8          112    81      85
9          114    69      71
10         121    78      82
11         122    84      87
12         123    92      95
13         124    73      76
14         125    89      91
15         126    67      70
16         127    80      84
17         128    94      93
18         129    76      78
19         130    83      86

In [56]:
departments = pd.DataFrame({
    "dept_id": [1, 2, 3, 4],
    "department": [
        "CSE",
        "EEE",
        "BBA",
        "Civil"
    ],
    "faculty": [
        "Engineering",
        "Engineering",
        "Business",
        "Engineering"
    ]
})

departments

   dept_id department      faculty
0        1        CSE  Engineering
1        2        EEE  Engineering
2        3        BBA     Business
3        4      Civil  Engineering

# 1. Create a dataframe contains students name,faculty and number on math and python

In [57]:
data = pd.merge(students, results, on='student_id')
data = pd.merge(data, departments, on='department')

data[['name', 'faculty', 'math', 'python']]

     name      faculty  math  python
0   Rahim  Engineering    85      90
1   Karim  Engineering    72      75
2   Hasan  Engineering    91      88
3   Nabil  Engineering    68      72
4  Tanvir  Engineering    77      80
5    Rafi     Business    88      92
6   Imran  Engineering    74      79
7    Arif  Engineering    95      96
8   Jahid     Business    81      85
9    Siam  Engineering    69      71

# 2. Department wise students count

In [58]:
data.groupby('department')['name'].count()

department
BBA    2
CSE    6
EEE    2
Name: name, dtype: int64

# 3. Faculty wise department count

In [59]:
data.groupby('faculty')['department'].nunique()

faculty
Business       1
Engineering    2
Name: department, dtype: int64

# 4. Find department wise highest number on each subject

In [60]:
data.groupby('department')[['math', 'python']].max()

            math  python
department
BBA           88      92
CSE           95      96
EEE           77      80

# 5. Find faculty wise highest number on each subject

In [61]:
data.groupby('faculty')[['math', 'python']].max()

             math  python
faculty
Business       88      92
Engineering    95      96

# Time-series

In [62]:
# use climate dataset
climate

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

# 1. convert time into datetime

In [63]:
climate['date'] = pd.to_datetime(climate['date'])
climate

           date   meantemp    humidity  wind_speed  meanpressure
0    2013-01-01  10.000000   84.500000    0.000000   1015.666667
1    2013-01-02   7.400000   92.000000    2.980000   1017.800000
2    2013-01-03   7.166667   87.000000    4.633333   1018.666667
3    2013-01-04   8.666667   71.333333    1.233333   1017.166667
4    2013-01-05   6.000000   86.833333    3.700000   1016.500000
...         ...        ...         ...         ...           ...
1457 2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458 2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459 2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460 2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461 2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

# 2. set date as index

In [64]:
climate = climate.set_index('date')
climate

             meantemp    humidity  wind_speed  meanpressure
date
2013-01-01  10.000000   84.500000    0.000000   1015.666667
2013-01-02   7.400000   92.000000    2.980000   1017.800000
2013-01-03   7.166667   87.000000    4.633333   1018.666667
2013-01-04   8.666667   71.333333    1.233333   1017.166667
2013-01-05   6.000000   86.833333    3.700000   1016.500000
...               ...         ...         ...           ...
2016-12-28  17.217391   68.043478    3.547826   1015.565217
2016-12-29  15.238095   87.857143    6.000000   1016.904762
2016-12-30  14.095238   89.666667    6.266667   1017.904762
2016-12-31  15.052632   87.000000    7.325000   1016.100000
2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 4 columns]

# 3. Select row of 13 january, 2015

In [65]:
climate.loc['2015-01-13']

meantemp          12.250
humidity          77.875
wind_speed         4.875
meanpressure    1017.125
Name: 2015-01-13 00:00:00, dtype: float64

# 4. Select rows contains in april 2017

In [66]:
#as the date was out of bound I thought to use try catch rather than showing error or empty table
try:
    print(climate.loc['2017-04'])
except KeyError:
    print("No data available for April 2017")

No data available for April 2017

# 5. Select rows from 11 september, 2014 to 25 september, 2014

In [67]:
climate.loc['2014-09-11':'2014-09-25']

             meantemp   humidity  wind_speed  meanpressure
date
2014-09-11  26.571429  85.714286   17.825000   1005.571429
2014-09-12  28.500000  73.000000    1.625000   1005.125000
2014-09-13  29.375000  68.250000    4.162500   1004.000000
2014-09-14  29.125000  65.500000    6.712500   1004.250000
2014-09-15  29.625000  63.125000    6.712500   1004.250000
2014-09-16  30.625000  65.125000    6.250000   1002.250000
2014-09-17  30.625000  61.875000    7.400000   1002.125000
2014-09-18  30.500000  62.375000    6.712500   1003.875000
2014-09-19  31.000000  56.625000    4.175000   1003.500000
2014-09-20  31.125000  55.750000    4.400000   1002.875000
2014-09-21  30.500000  54.875000    5.562500   1003.625000
2014-09-22  30.625000  50.000000   13.437500   1004.500000
2014-09-23  31.000000  47.000000   30.685714   1004.285714
2014-09-24  29.625000  53.000000    8.100000   1006.250000
2014-09-25  30.000000  52.500000    9.725000   1007.750000

# 6. Calculate month-wise average windspeed

In [68]:
climate['wind_speed'].resample('ME').mean()

date
2013-01-31     4.833913
2013-02-28     7.474090
2013-03-31     8.757270
2013-04-30     8.046385
2013-05-31     8.943452
2013-06-30     9.593929
2013-07-31     7.358698
2013-08-31     7.384347
2013-09-30     7.593425
2013-10-31     2.836110
2013-11-30     4.252242
2013-12-31     4.986002
2014-01-31     5.560580
2014-02-28     6.402232
2014-03-31     7.123963
2014-04-30     8.868631
2014-05-31     8.576555
2014-06-30    10.111250
2014-07-31     7.528590
2014-08-31     7.665360
2014-09-30     8.054940
2014-10-31     3.988191
2014-11-30     3.126667
2014-12-31     4.133756
2015-01-31     5.261290
2015-02-28     6.317985
2015-03-31     7.701210
2015-04-30     8.530000
2015-05-31     9.065495
2015-06-30     8.769167
2015-07-31     8.580703
2015-08-31     5.477031
2015-09-30     7.229048
2015-10-31     4.930012
2015-11-30     2.117500
2015-12-31     3.795392
2016-01-31     4.285177
2016-02-29     5.950592
2016-03-31     7.204904
2016-04-30     9.687357
2016-05-31     9.506423
2016-06-30     9.052079
2016-07-31     6.207018
2016-08-31     7.168392
2016-09-30     7.508029
2016-10-31     7.291021
2016-11-30     5.993723
2016-12-31     6.132705
2017-01-31     0.000000
Freq: ME, Name: wind_speed, dtype: float64

# 7. Calculate month-wise highest meantemp

In [69]:
climate['meantemp'].resample('ME').max()

date
2013-01-31    16.500000
2013-02-28    20.800000
2013-03-31    29.166667
2013-04-30    32.125000
2013-05-31    38.714286
2013-06-30    37.166667
2013-07-31    33.857143
2013-08-31    32.500000
2013-09-30    32.750000
2013-10-31    30.833333
2013-11-30    23.428571
2013-12-31    18.000000
2014-01-31    16.625000
2014-02-28    19.625000
2014-03-31    26.250000
2014-04-30    33.250000
2014-05-31    35.250000
2014-06-30    38.500000
2014-07-31    36.625000
2014-08-31    34.125000
2014-09-30    31.250000
2014-10-31    31.000000
2014-11-30    24.125000
2014-12-31    25.000000
2015-01-31    15.125000
2015-02-28    23.125000
2015-03-31    28.500000
2015-04-30    32.875000
2015-05-31    37.750000
2015-06-30    37.625000
2015-07-31    35.714286
2015-08-31    32.625000
2015-09-30    33.000000
2015-10-31    30.000000
2015-11-30    24.000000
2015-12-31    19.250000
2016-01-31    20.142857
2016-02-29    23.875000
2016-03-31    30.000000
2016-04-30    35.687500
2016-05-31    38.272727
2016-06-30    38.200000
2016-07-31    34.187500
2016-08-31    33.809524
2016-09-30    33.444444
2016-10-31    33.269231
2016-11-30    25.640000
2016-12-31    21.208333
2017-01-31    10.000000
Freq: ME, Name: meantemp, dtype: float64

# 8. Year-wise maximum, minimum and average humidity

In [70]:
climate['humidity'].resample('YE').agg(['max', 'min', 'mean'])

                   max         min        mean
date
2013-12-31   94.000000   15.857143   63.046292
2014-12-31   96.857143   20.875000   59.767942
2015-12-31   98.000000   13.428571   61.430490
2016-12-31   94.300000   18.466667   58.740174
2017-12-31  100.000000  100.000000  100.000000

# 9. A new column contains previous 10 days average meantemp

In [71]:
climate['previous_10_days_avg'] = climate['meantemp'].rolling(10).mean()

climate[['meantemp', 'previous_10_days_avg']]

             meantemp  previous_10_days_avg
date
2013-01-01  10.000000                   NaN
2013-01-02   7.400000                   NaN
2013-01-03   7.166667                   NaN
2013-01-04   8.666667                   NaN
2013-01-05   6.000000                   NaN
...               ...                   ...
2016-12-28  17.217391             17.107129
2016-12-29  15.238095             16.845224
2016-12-30  14.095238             16.274748
2016-12-31  15.052632             15.975011
2017-01-01  10.000000             15.246440

[1462 rows x 2 columns]